### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-bncurve#1]
# arith.nim

1.
https://github.com/status-im/nim-bncurve/blob/ea38d7b5b8441376e6c1b170cf48d6939e6a2ef4/bncurve/arith.nim#L18-L21

~It seems like randomBytes for openarray is returning the number of elements in the openarray instead of the number of bytes set, naively I would expect the number of bytes set.~ Scratch that, uint64 are 8 x 8 bytes, that threw me off.

2. noinit is not needed if there is no return value :
https://github.com/status-im/nim-bncurve/blob/ea38d7b5b8441376e6c1b170cf48d6939e6a2ef4/bncurve/arith.nim#L18
https://github.com/status-im/nim-bncurve/blob/ea38d7b5b8441376e6c1b170cf48d6939e6a2ef4/bncurve/arith.nim#L27
https://github.com/status-im/nim-bncurve/blob/ea38d7b5b8441376e6c1b170cf48d6939e6a2ef4/bncurve/arith.nim#L34

Furthermore following https://github.com/nim-lang/Nim/issues/8745, it shouldn't be needed anymore for ref objects, and for stack I think we always want to zero-init in crypto (and there are some GCC/LLVM flag to enforce that in C/C++).

3. https://github.com/status-im/nim-bncurve/blob/ea38d7b5b8441376e6c1b170cf48d6939e6a2ef4/bncurve/arith.nim#L41-L43

Can be:
```
proc zero*(t: typedesc[BNU256]): BNU256 {.inline.} =
  ## Return zero 256bit integer.
  discard
```

4. setBit, to be tested but here are 2 constant-time alternatives (w.r.t. a) if needed
From:
```Nim
proc setBit*(a: var openarray[uint64], n: int,
             to: bool): bool {.inline, noinit.} =
  ## Set bit of integer ``a`` at position ``n`` to value ``to``.
  if n >= 256:
    return
  let part = n shr 6
  let bit = n - (part shl 6)
  if to:
    a[part] = a[part] or (1'u64 shl bit)
  else:
    a[part] = a[part] and not(1'u64 shl bit)
  result = true
```

to

```Nim
func setBitAlt1(a: var BNU256, n: int, to: bool): bool {.inline.}=
  if n >= 256:
    return
  let
    index = n and 63
    part = n shr 6
    value = to.uint64

  a[part] = a[part] and not(1'u64 shl index) or (value shl index)
  result = true
```
Or
```Nim
template `-`(x: uint64): uint64 =
  x.not + 1
func setBitAlt2(a: var BNU256, n: int, to: bool): bool {.inline.}=
  if n >= 256:
    return
  let
    index = n and 63
    part = n shr 6
    value = to.uint64

  a[part] = a[part] xor ((-value xor a[part]) and (1'u64 shl index))
  result = true
```

5. Not sure what macDigit is, I suppose it's part of Montgomery reduction?

# fp, groups, fq2, fq6, fq12

Too unfamiliar at the moment for review.

# Final thoughts

Great job!

**Comment by cheatfate** [comment]
Points `1, 2, 3, 4` has been fixed in https://github.com/status-im/nim-bncurve/pull/2
